apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-test
  labels:
    app: metrics-test
spec:
  replicas: 1
  template:
    metadata:
      name: metrics-test
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus_io_path: /metrics
        prometheus_io_port: '8080'
        prometheus_io_scheme: https
        prometheus_io_scrape: 'true'
      labels:
        app: metrics-test
    spec:
      containers:
        - name: metrics-test
          ports:
            - containerPort: 8080
          image: quay.io/brancz/prometheus-example-app:v0.3.0
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: metrics-test
