global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: 'istio-prometheus'
    honor_labels: true
    metrics_path: '/federate'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['istio-system']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'workload:(.*)'
        target_label: __name__
        action: replace
    params:
      'match[]':
        - '{__name__=~"workload:(.*)"}'
        - '{__name__=~"pilot(.*)"}'