apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-http
spec:
  hosts:
    - test
  location: MESH_EXTERNAL
  ports:
    - number: 8080
      name: http
      protocol: HTTP
  resolution: DNS
  endpoints:
    - address: 192.168.1.183
      ports:
        http: 8080

---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: test
#spec:
#  hosts:
#    - test
#  http:
#    - route:
#        - destination:
#            host: test
#      retries:
#        attempts: 0
#---
kind: Service
apiVersion: v1
metadata:
  name: test
  namespace: firstprj
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: test
subsets:
  - addresses:
      - ip: 192.168.1.183
    ports:
      - port: 8080