apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-client
  labels:
    app: rate-client
spec:
  replicas: 1
  template:
    metadata:
      name: rate-client
      labels:
        app: rate-client
    spec:
      containers:
        - name: rate-client
          image: d4rkest/rate-client:0.0.1
          imagePullPolicy: Always
          command:
            - '-dial_string=rate-limiter:8081'
            - '-domain=proxy-app-sidecar-inbound'
            - '-descriptors=remote_address=1.1.1.1'
            - '-repeat=5000'
      restartPolicy: Always
  selector:
    matchLabels:
      app: rate-client
