kind: Deployment
apiVersion: apps/v1
metadata:
  name: curl
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
      version: 7.71.1
  template:
    metadata:
      labels:
        app: curl
        version: 7.71.1
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
        - name: curl
          image: 'curlimages/curl:7.71.1'
          args:
            - 192.168.1.13:9200