apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: elastic-se
spec:
  hosts:
    - elastic.istio-system
  location: MESH_EXTERNAL
  ports:
    - number: 9200
      name: http
      protocol: HTTP
  resolution: DNS
  endpoints:
    - address: 192.168.1.13
      ports:
        http: 9200
